server:
  servlet:
    context-path: /@project.artifactId@
  port: '8086'

spring:
  datasource:
    url: jdbc:h2:mem:todolist
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true